openapi: 3.1.0
info:
  title: InstituiçãoApi
  description: Api de instituições da SIGAE OPEN SOURCE
  version: v1
paths:
  /api/Escola:
    get:
      tags:
        - Intituicoes-Escola
      responses:
        '200':
          description: Success
  '/api/Escola/{id}':
    get:
      tags:
        - Intituicoes-Escola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components: { }