openapi: 3.1.0
info:
  version: 0.0.1
  title: SIGAE
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: contact@example.com
    url: http://example.com/contact
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
  x-logo:
    url: 'https://cdnportaliuprd.portalinstitutounibanco.org.br/core/views/unibanco/images/cover-acontece.jpg'
    altText: Instituto Unibanco SIGAE
  description: >
    Estas são as APIs do SIGAE
